"""
Shared state models for Somnus.

Architecture note:
  Every agent in Somnus reads from and writes to a SharedState object.
  This single-state-tree pattern keeps agents decoupled — each specialist
  only knows about the fields it cares about, and the orchestrator is
  responsible for passing the current state in and collecting the mutated
  state back out.  No agent talks directly to another; all coordination
  happens through SharedState.
"""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class UserPreferences(BaseModel):
    """Persisted user settings loaded at session start."""
    goals: List[str] = []
    disliked_audio: List[str] = []
    preferred_audio: List[str] = []
    target_wake_time: str = "07:30"
    # Controls how aggressively agents intervene when disturbances are detected.
    intervention_aggressiveness: Literal["low", "medium", "high"] = "medium"


class SensorSnapshot(BaseModel):
    """One moment-in-time reading from wearable / environment sensors."""
    timestamp: str
    heart_rate: Optional[float] = None
    hrv: Optional[float] = None                # Heart-rate variability (ms)
    movement: Optional[float] = None           # 0–1 normalized movement score
    noise_db: Optional[float] = None
    light_level: Optional[float] = None        # 0–1 normalized lux
    breathing_rate: Optional[float] = None     # breaths per minute


class SleepState(BaseModel):
    """
    Person C ownership: current inferred sleep phase and wake fragility.

    Default semantics:
      - phase="unknown": no reliable phase classification yet.
      - confidence=0.0: classifier confidence is unknown/lowest certainty.
      - wake_risk=0.0: no imminent wake-risk evidence has been detected yet.
    """
    phase: Literal["awake", "light", "deep", "rem", "unknown"] = "unknown"
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="0–1 model confidence in the current sleep phase label.",
    )
    wake_risk: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="0–1 probability of waking in the next evaluation window.",
    )
    disturbance_reason: Optional[str] = None

    @field_validator("disturbance_reason")
    @classmethod
    def validate_disturbance_reason(cls, value: Optional[str]) -> Optional[str]:
        """Keep disturbance_reason nullable, but never persist empty strings."""
        if value is None:
            return None
        if not value.strip():
            raise ValueError("disturbance_reason must be a non-empty string when present")
        return value


class ActiveIntervention(BaseModel):
    """
    Person C ownership: intervention currently running for the user.

    Default semantics:
      - type="none" with intensity=0.0 means no intervention is active.
      - intensity is normalized intervention strength (for audio, this maps to
        effective volume; for pacing/ramp, it maps to stimulation strength).
    """
    type: Literal[
        "none", "brown_noise", "white_noise", "pink_noise",
        "rain", "waves", "breathing_pace", "wake_ramp"
    ] = "none"
    intensity: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="0–1 normalized intervention strength.",
    )
    started_at: Optional[str] = None
    rationale: Optional[str] = None  # Human-readable reason chosen by an agent

    @model_validator(mode="after")
    def validate_none_semantics(self) -> "ActiveIntervention":
        """Formalize Team C contract: no intervention implies zero intensity."""
        if self.type == "none" and self.intensity != 0.0:
            raise ValueError("active_intervention.intensity must be 0.0 when type is 'none'")
        return self


class JournalEntry(BaseModel):
    """One night's retrospective data, filled in by the user at morning."""
    date: str                          # ISO date string, e.g. "2026-03-14"
    rested_score: int                  # 1–10 self-reported restedness
    awakenings_reported: int
    notes: str = ""


class NightlyPlan(BaseModel):
    """
    Pre-sleep plan generated by the Strategist agent.

    Captured before the sleep session starts and used by other agents
    throughout the night to stay aligned with the user's goals.

    Outer-loop fields (populated by apply_policy_to_state at session start):
      blocked_interventions — types suppressed due to poor policy scores from
                              prior nights.  The intervention agent treats these
                              identically to disliked_audio but logs the reason.
      policy_guidance_note  — human-readable summary of what the outer loop
                              injected, for debugging and display.
    """
    target_bedtime: str = "23:00"
    target_wake_time: str = "07:00"
    sleep_goal: str = ""             # e.g. "deep sleep focus", "max REM"
    notes: str = ""
    # Ordered list of intervention types the strategist recommends trying first.
    preferred_intervention_order: List[str] = Field(
        default_factory=lambda: ["brown_noise", "breathing_pace", "rain"]
    )
    # Outer-loop policy enforcement: types blocked from use tonight.
    # Set by apply_policy_to_state(); never written by the strategist.
    blocked_interventions: List[str] = Field(default_factory=list)
    # Trace of outer-loop guidance applied at session start (empty if no policy).
    policy_guidance_note: str = ""


class SharedState(BaseModel):
    """
    Central state object passed between all Somnus agents.

    Orchestration pattern:
      1. Orchestrator loads SharedState (from cache / session store).
      2. Relevant agents are called with the current SharedState.
      3. Each agent returns an updated SharedState (or a partial patch).
      4. Orchestrator merges patches and persists the result.

    Person C owns and maintains the following state sections:
      - sleep_state: current phase classification + wake-risk confidence.
      - active_intervention: current intervention type/intensity/rationale.
      - hypotheses: append-only reasoning artifacts from real-time and morning
        agents, validated to include source and optional timing/signal/context.
      - journal-derived personalization behavior: represented by the interaction
        between journal_history, hypotheses, and downstream NightlyPlan updates.
        Journal insights can influence future intervention ordering/intensity
        choices without changing API shape.

    This design lets agents be pure functions (SharedState -> SharedState),
    making them easy to test in isolation and safe to run concurrently when
    their fields don't overlap.
    """
    user_id: str
    preferences: UserPreferences
    latest_sensor: Optional[SensorSnapshot] = None
    sleep_state: SleepState = Field(default_factory=SleepState)
    active_intervention: ActiveIntervention = Field(default_factory=ActiveIntervention)
    nightly_plan: NightlyPlan = Field(default_factory=NightlyPlan)
    # Team C-owned hypothesis log with explicit source contracts and aliases.
    hypotheses: List[Dict[str, Any]] = Field(default_factory=list)
    journal_history: List[JournalEntry] = Field(default_factory=list)

    @field_validator("hypotheses")
    @classmethod
    def validate_hypotheses_shape(cls, hypotheses: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Validate each hypothesis entry while preserving legacy payload keys.

        Required shape:
          - source: non-empty string identifying producer agent/component.

        Source-specific contract (aligned with app/pipeline_contracts.py writes):
          - sensor_interpreter (writes hypotheses during tick):
            requires timing anchor (timestamp or date) and signal payload
            (signal_summary or legacy alias "signals").
          - journal_reflection (writes hypotheses during morning):
            requires reflection context via decision_context or legacy aliases
            "reflection" / "rationale".

        Optional compatible keys:
          - timestamp or date: time anchor for the hypothesis.
          - signal_summary (or legacy alias "signals"): short signal digest.
          - decision_context (or legacy aliases "reflection" / "rationale"):
            decision rationale, pattern summary, or recommendation context.

        Backward compatibility:
          - Additional keys are allowed and preserved.
          - Older entries without timing/context keys remain valid.
        """
        if not isinstance(hypotheses, list):
            raise TypeError("hypotheses must be a list")

        for i, entry in enumerate(hypotheses):
            if not isinstance(entry, dict):
                raise TypeError(f"hypotheses[{i}] must be a dict")

            source = entry.get("source")
            if not isinstance(source, str) or not source.strip():
                raise ValueError(f"hypotheses[{i}].source must be a non-empty string")

            for key in ("timestamp", "date"):
                if key in entry and (not isinstance(entry[key], str) or not entry[key].strip()):
                    raise ValueError(f"hypotheses[{i}].{key} must be a non-empty string when present")

            signal_summary = entry.get("signal_summary", entry.get("signals"))
            if signal_summary is not None and not isinstance(signal_summary, (str, dict)):
                raise ValueError(
                    f"hypotheses[{i}].signal_summary/signals must be a string or object when present"
                )

            decision_context = entry.get(
                "decision_context",
                entry.get("reflection", entry.get("rationale")),
            )
            if decision_context is not None and not isinstance(decision_context, (str, dict)):
                raise ValueError(
                    f"hypotheses[{i}].decision_context/reflection/rationale must be a string or object when present"
                )

            if source == "sensor_interpreter":
                if not (entry.get("timestamp") or entry.get("date")):
                    raise ValueError(
                        f"hypotheses[{i}] from sensor_interpreter must include timestamp or date"
                    )
                if signal_summary is None:
                    raise ValueError(
                        f"hypotheses[{i}] from sensor_interpreter must include signal_summary or signals"
                    )

            if source == "journal_reflection" and decision_context is None:
                raise ValueError(
                    f"hypotheses[{i}] from journal_reflection must include decision_context/reflection/rationale"
                )

        return hypotheses
