"""
Shared state models for Somnus.

Architecture note:
  Every agent in Somnus reads from and writes to a SharedState object.
  This single-state-tree pattern keeps agents decoupled — each specialist
  only knows about the fields it cares about, and the orchestrator is
  responsible for passing the current state in and collecting the mutated
  state back out.  No agent talks directly to another; all coordination
  happens through SharedState.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal, Dict


class UserPreferences(BaseModel):
    """Persisted user settings loaded at session start."""
    goals: List[str] = []
    disliked_audio: List[str] = []
    preferred_audio: List[str] = []
    target_wake_time: str = "07:30"
    # Controls how aggressively agents intervene when disturbances are detected.
    intervention_aggressiveness: Literal["low", "medium", "high"] = "medium"


class SensorSnapshot(BaseModel):
    """One moment-in-time reading from wearable / environment sensors."""
    timestamp: str
    heart_rate: Optional[float] = None
    hrv: Optional[float] = None                # Heart-rate variability (ms)
    movement: Optional[float] = None           # 0–1 normalized movement score
    noise_db: Optional[float] = None
    light_level: Optional[float] = None        # 0–1 normalized lux
    breathing_rate: Optional[float] = None     # breaths per minute


class SleepState(BaseModel):
    """Current inferred sleep phase and associated risk scores."""
    phase: Literal["awake", "light", "deep", "rem", "unknown"] = "unknown"
    confidence: float = 0.0          # 0–1 model confidence in phase label
    wake_risk: float = 0.0           # 0–1 probability of waking in next window
    disturbance_reason: Optional[str] = None


class ActiveIntervention(BaseModel):
    """Describes whatever audio/pacing intervention is currently running."""
    type: Literal[
        "none", "brown_noise", "white_noise", "pink_noise",
        "rain", "waves", "breathing_pace", "wake_ramp"
    ] = "none"
    intensity: float = 0.0           # 0–1 volume / strength
    started_at: Optional[str] = None
    rationale: Optional[str] = None  # Human-readable reason chosen by an agent


class JournalEntry(BaseModel):
    """One night's retrospective data, filled in by the user at morning."""
    date: str                          # ISO date string, e.g. "2026-03-14"
    rested_score: int                  # 1–10 self-reported restedness
    awakenings_reported: int
    notes: str = ""


class NightlyPlan(BaseModel):
    """
    Pre-sleep plan generated by the Strategist agent.

    Captured before the sleep session starts and used by other agents
    throughout the night to stay aligned with the user's goals.
    """
    target_bedtime: str = "23:00"
    target_wake_time: str = "07:00"
    sleep_goal: str = ""             # e.g. "deep sleep focus", "max REM"
    notes: str = ""
    # Ordered list of intervention types the strategist recommends trying first.
    preferred_intervention_order: List[str] = Field(
        default_factory=lambda: ["brown_noise", "breathing_pace", "rain"]
    )


class SharedState(BaseModel):
    """
    Central state object passed between all Somnus agents.

    Orchestration pattern:
      1. Orchestrator loads SharedState (from cache / session store).
      2. Relevant agents are called with the current SharedState.
      3. Each agent returns an updated SharedState (or a partial patch).
      4. Orchestrator merges patches and persists the result.

    This design lets agents be pure functions (SharedState -> SharedState),
    making them easy to test in isolation and safe to run concurrently when
    their fields don't overlap.
    """
    user_id: str
    preferences: UserPreferences
    latest_sensor: Optional[SensorSnapshot] = None
    sleep_state: SleepState = Field(default_factory=SleepState)
    active_intervention: ActiveIntervention = Field(default_factory=ActiveIntervention)
    nightly_plan: NightlyPlan = Field(default_factory=NightlyPlan)
    # Free-form hypotheses logged by the disturbance / strategist agents.
    hypotheses: List[Dict] = Field(default_factory=list)
    journal_history: List[JournalEntry] = Field(default_factory=list)
